Public Enum State
    INIT
    CHOIX_250
    CHOIX_500
    CHOIX_1000
    PATE
    CUISSON
    MODIFIER_NOM
    AJOUTER_PIZZA_RECOMMANDE1
    AJOUTER_PIZZA_RECOMMANDE2
    AJOUTER_PIZZA_CAT
    PASSER_COMMANDE
    RETOUR_EDITION_COMMANDE
    CONSULTER_CAT1
    CONSULTER_CAT2
    CONSULTER_CAT3
    DEROULER_CLICKED
    ENROULER_CLICKED
    BASE_CLICKED
    SUPPRIMER_CLICKED
    PERSONNALISER_CLICKED
    CHECKBOX_CHECKED
    CHECKBOX_UNCHECKED
End Enum
